### ISSUE TITLE
CSV export: Save last export directory

### ISSUE THREAD

**Issue by OLibutzki** [kieker-monitoring/kieker-trace-diagnosis-ui#3]
When a csv export is performed, the tool should save the location which is selected by the users. Whenever another export is triggered the dialog should preselect this saved location.

**Comment by nils-christian** [comment]
Hello Oliver,

Thank you for the hint. You are correct - the tool should indeed save the last export location. I will implement this in Version 3.0.0 of the tool.

Best regards

  Nils

**Comment by nils-christian** [comment]
Fixed in c070ee36696271a98989be29628484ffb660d05c. Please note that further issues will be handled in our Kieker Jira (https://kieker-monitoring.atlassian.net).
